var colours = ['green', 'red', 'yellow', 'blue']; //this is used for generate random colours
var randomColours = []; //this save the random colours generated by the array above.
var clickedColours = []; //the colours inside here must be compared with the random colours generated above.
var c = 0;

$("body").keydown(function() {
  if(randomColours.length==0) {
    random();
  }
});

$(".btn").click(function(event) {
  var colour = event.currentTarget.id;
  var audio = new Audio("./sounds/"+colour+".mp3");
  audio.play();
  $("#"+colour).addClass("pressed");
  setTimeout(function(){$("#"+colour).removeClass("pressed");},100);
  test(colour);
});

function random() {
  var randomNumber = Math.floor(Math.random()*4);
  var ranCol = colours[randomNumber];
  randomColours.push(ranCol);
  $("#"+ranCol).fadeOut(100).fadeIn(100);
  var audio = new Audio("./sounds/"+ranCol+".mp3");
  audio.play();
  $("h1").text("Level "+randomColours.length);
}

function test(para) {
  var colour = para;
  clickedColours.push(colour);
  compare(colour);
}

function compare(colour) {
  if (randomColours[c]==colour) {
    c++;
    if(c==randomColours.length) {
      c=0;
      setTimeout(random,1000);
    }
  } else {
    c=0;
    randomColours=[];
    clickedColours=[];
    var audio = new Audio("./sounds/wrong.mp3");
    audio.play();
    $("body").addClass("game-over");
    setTimeout(function(){$("body").removeClass("game-over");},100);
    $("h1").text("Game Over, Press Any Key to Restart");
  }
}
